### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by gnurenga** [AllenDowney/ThinkPython2#24] opened 2016-10-12 05:05 UTC
- I cloned the latest master branch a2b4cb70b9c9c666640e6142ef6329c54cd78c0b
- I was trying to build book but i got following error

```
rengaraj@toad:~/ThinkPython2/book$ make
makeindex book.idx
Input index file book.idx not found.
Usage: makeindex [-ilqrcgLT] [-s sty] [-o ind] [-t log] [-p num] [idx0 idx1 ...]
Makefile:20: recipe for target 'all' failed
make: *** [all] Error 1

```
- There is no book.idx file found inside the book directory.

**Comment by emansije** [comment] 2016-11-23 20:39
I got the same error. After examining the file `book/Makefile`, I decided to comment line 20 (`makeindex book.idx`), just to see what happened. Running `make` generated the file `book.idx`, but it complained about another file missing:
```
! LaTeX Error: File `hevea.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
```
I pressed Enter and it continued a bit further until it stopped again on a `?` prompt. I kept pressing Enter until it reached the end with the following message:
```
Output written on book.pdf (246 pages, 823775 bytes).
Transcript written on book.log.
Makefile:20: recipe for target 'all' failed
make: *** [all] Error 1
```
The resulting `book.pdf` file had the contents missing, but on a second run of `make`, the contents were generated, since it already had a `book.idx` file. The resulting `book.pdf` was never perfect, with some gibberish in the first page:
```
a:linkcolor:black; p+pmargin-top:1em;margin-bottom:1em imgborder:0px
[ALT="Previous"]back.png [ALT="Up"]up.png [ALT="Next"]next.png
```
and the first chapter starting with zero, instead of 1.

**Comment by calcisme** [comment] 2017-01-12 12:40
This problem is being caused by a missing line in the Makefile. There should be another "pdflatex book" before "makeindex book.idx". You may also want to edit out the line "evince thinkpython2.pdf", as not everyone uses evince to read pdf files.

As for the hevea.sty file being missing, you can download a copy from http://hevea.inria.fr. Ideally, this would be included in the book directory.

**Comment by emansije** [comment] 2017-01-12 16:47
Spot on!
I added another `pdflatex book`, as you suggested, and installed `hevea` from the repositories (I'm on Ubuntu). I also changed `evince thinkpython2.pdf` into `xdg-open thinkpython2.pdf`, to make it more universal. After that, everything worked like a charm.

**Comment by AllenDowney** [comment] 2017-01-16 19:28
That all sounds fine.  Do you want to send me a PR?

On Thu, Jan 12, 2017 at 11:47 AM, Emanuel de Jesus <notifications@github.com

**Comment by calcisme** [comment] 2017-01-18 23:43
This is my first time doing a pull request, so I hope it is as intuitive as it seems. I suggested the changes to the Makefile and added hevea.sty. Let me know if I did things incorrectly. Thanks.

**Comment by AllenDowney** [comment] 2017-01-19 14:41
Merged.  Thanks very much!

**Closed** 2019-06-21 15:34 UTC
